import math
from .models import LSystemConfig
from typing import Dict, Any

def card_generator():
    """Process the svg generated by the processor to make the draft e-invitation card."""
    return None 